### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ravikiran97** [kuthulas/SMS#10]
As a staff when I change the url to /checkins (which is the reports page only accessible by the ADMIN),  I am able to edit or destroy reports as a Staff.

**Comment by swarna-k** [comment]
d report tab itself is nt visible in staff login ! but i can make the
changes in d main code for this . ill do it at 7pm as i am right now
working fr my lab. or you can do it too. go to the view for report and
vhange the if statement as if adminlogged in ? see the syntax

**Comment by kuthulas** [comment]
Nice find. These issues are not to be dealt with in the views. Use cancan (the ability.rb file). No shortcuts please. Minimize the "if logged in" parts in views.

**Comment by swarna-k** [comment]
thanks for the tip kumaran! Will do that.

**Comment by kuthulas** [comment]
I believe this is fixed.
