### ISSUE TITLE
Events on Staff Home Page

### ISSUE THREAD

**Issue by mahathi92v** [kuthulas/SMS#4]
Only events scheduled for that particular day should be visible to the check-in staff. This can be addressed in three ways:
1. completely remove the events tab and display the events scheduled for the day on the staff home page itself or
2. Keep the staff home page empty (welcome message/ or some other info) and display the events scheduled for that particular day separately in the events tab.
3. Any of the above two with all events visible but only events for the present day active

**Comment by kuthulas** [comment]
We no longer have event management links on home page. Current day events are listed on the events page for staff. Home page with upcoming events is just for information.

**Comment by kuthulas** [comment]
Option 1 has been implemented.
