### ISSUE TITLE
Verify the number of digits in UIN

### ISSUE THREAD

**Issue by mahathi92v** [kuthulas/SMS#6]
In the staff log in while manually entering the number the following bugs are present:
1. When manually entering the UIN a check has to be put so that entered UIN has 9 digits
2. The entered number is the magnetic card identification number which should be 16 digits 
3. Pop box does not appear when card is not found 
4. only characters should be accepted for names (numbers are also accepted)

**Comment by kuthulas** [comment]
Done.
