### ISSUE TITLE
New Student 

### ISSUE THREAD

**Issue by mahathi92v** [kuthulas/SMS#9]
Creates new student even though none of the details are provided (all spaces left blank and clicking on create)
Same case when it comes to new event (but shows error when trying to navigate after creating the event)

**Comment by swarna-k** [comment]
I have made the following changes -

staff logged in

home page - displays all upcoming events but no links provided

events page - displays only those events which are scheduled for today
(current date) and has check in link.

**Comment by swarna-k** [comment]
also, i am planning to remove students and cards tabs for staff pages.
staff will have only access to home page and events page with check in
priviledges only.

**Comment by kuthulas** [comment]
User, Student and Event validations in place. Test if possible.
